package io.noks.smallpractice.objects.duel;

public class RedRoverDuel {
	// TODO: learn how RedRover works
	
	// CHOOSE  REDROVER PARTY GAME
	// CHOOSE THE SECOND LEADER
	// PICKUP MATES (TURN BY TURN!!!)
	// WHEN THE PICKUP IS DONE LAUNCH DUEL
	// GIVE A BOOK TO SELECT PLAYERS THAT WILL 1V1
	// WHEN LEADERS HAS CHOOSEN THEIR PLAYER LAUNCH DUEL
	// WHEN GETTING KILLED PLAYER IS REMOVED FROM THE DUEL!
}
