# For secret informations :) #
database:
  address: "localhost"
  name: ""
  username: ""
  password: ""
server-domain-name: "noks.io"
send-join-and-quit-message-to-op: false
# \n for newLine
tab:
  header: "Noks.io"
  footer: "SmallPractice"
