# For secret informations :) #
database:
  address: "localhost"
  name: ""
  username: ""
  password: ""
clear-chat-on-join: true
server-domain-name: "devmc.noks.io"
enable-in-fight-scoreboard: false # FUCK IN FIGHT SCOREBOARD #
