main: us.noks.smallpractice.Main
name: SmallPractice
version: 2.0
author: Noksio
depend: [PermissionsEx]
commands:
  duel:
  accept:
  deny:
  build:
  ping:
    aliases: [ms]
  inventory:
    aliases: [inv]
  spawn:
  seeall:
  report:
  spectate:
    aliases: [spec]
  mod:
  party:
    aliases: [team]
  forceduel:
    aliases: [fd]
  day:
  night:
  resettime:
  roll:
  