main: us.noks.smallpractice.Main
name: SmallPractice
version: 1.45
author: Noksio
depend: [PermissionsEx]
commands:
  duel:
  accept:
  build:
  ping:
  inventory:
  spawn:
  seeall:
  report:
  spectate:
    aliases: [spec]
  mod:
  