main: io.noks.smallpractice.Main
name: SmallPractice
version: 2.0
author: Noksio
website: github.com/iamnoksio/SmallPractice
commands:
  duel:
  accept:
  deny:
  build:
  ping:
    aliases: [ms]
  inventory:
    aliases: [inv]
  spawn:
  seeall:
  report:
  spectate:
    aliases: [spec]
  mod:
  party:
    aliases: [team, p]
  forceduel:
    aliases: [fd]
  sunrise:
  day:
  sunset:
  night:
  resettime:
    aliases: [timereset]
  roll:
  mention:
  namemc:
  elo:
    aliases: [stats]
  